---
# Source: test/templates/configmap-xml.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  labels:
    app: nginx
    env: dev
data:
  sample.xml: |
    <note>
    <to>Tove</to>
    <from>Jani</from>
    <heading>Reminder</heading>
    <body>Don't forget me this weekend!</body>
    </note>
---
# Source: test/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  labels:
    app: nginx
    env: dev
data:
  config.yaml: |
    database:
      name: ui-dev
    logfile: /app/var/log.txt
    timeout: 10s
---
# Source: test/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-service
  labels:
    app: nginx
    env: dev
spec:
  ports:
  - port: 80
  selector:
    nginx
---
# Source: test/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    env: dev
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          limits:
            cpu: 2
            memory: 500mi
          requests:
            cpu: 0.2
            memory: 500mi
        ports:
        - containerPort: 80
