---
# Source: test/templates/configmap-xml.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  labels:
    app: nginx
    env: preprod
data:
  sample.xm: |
---
# Source: test/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  labels:
    app: nginx
    env: preprod
data:
  config.yaml: |
    database:
      name: ui-dev
    logfile: /app/var/log.txt
    timeout: 6s
---
# Source: test/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-service
  labels:
    app: nginx
    env: preprod
spec:
  ports:
  - port: 80
  selector:
    nginx
---
# Source: test/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    env: preprod
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
        env: preprod
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          limits:
            cpu: 2
            memory: 500mi
          requests:
            cpu: 0.2
            memory: 500mi
        ports:
        - containerPort: 80
